"""Regenerate the pitchers-list JS from saa_pitchers_full.csv.

Produces:
  - js/pitchers-embed.js  SAA_DATA + SAA_BUBBLE  (top N + the next BUBBLE_N)
  - js/pitchers-career.js SAA_CAREER             (career line per rank, 1..N)

saa_pitchers_full.csv is the committed full ranked pool from
build_pitchers_saa.py; taking the top N reproduces its numbers exactly.
"""
import csv
import json
import re
from pathlib import Path

HERE = Path("/Users/martinjenkins/Personal/Claude Projects/RHOF Alternative War")
N = 150
BUBBLE_N = 20   # ranks N+1 .. N+BUBBLE_N shown in the "On the bubble" strip

full = list(csv.DictReader(open(HERE / "saa_pitchers_full.csv")))
top = full[:N]

# ---- SAA_DATA ----
data = []
for r in top:
    data.append({
        "rank": int(r["rank_saa"]),
        "name": r["name"],
        "ip": round(float(r["IP"])),
        "seasons": int(round(float(r["qualifying_seasons"]))),
        "saa": round(float(r["SAA_total"]), 2),
        "rate": round(float(r["SAA_rate"]), 3),
        "era": round(float(r["z_era"]), 2),
        "whip": round(float(r["z_whip"]), 2),
        "k9": round(float(r["z_k9"]), 2),
        "wpct": round(float(r["z_wpct"]), 2),
        "sv": round(float(r["z_sv"]), 2),
        "hof": r["hof"] == "True",
        # NeL flag = a Negro Major League season (40+ IP) actually feeds this
        # pitcher's ranking, not merely a cameo -- see build_pitchers_saa.py.
        "nel": r["is_nel_ranked"] == "True",
        "role": r["role"],
    })

# ---- SAA_BUBBLE: the next BUBBLE_N, just outside the cut ----
bubble = [{
    "rank": int(r["rank_saa"]),
    "name": r["name"],
    "saa": round(float(r["SAA_total"]), 2),
    "hof": r["hof"] == "True",
    "nel": r["is_nel_ranked"] == "True",
} for r in full[N:N + BUBBLE_N]]

embed = HERE / "js/pitchers-embed.js"
src = embed.read_text()
line = "const SAA_DATA = " + json.dumps(data, separators=(",", ":")) + ";"
src, n = re.subn(r"const SAA_DATA = \[.*?\];", lambda _m: line, src, count=1, flags=re.S)
assert n == 1, "SAA_DATA line not found in pitchers-embed.js"
bub_line = "const SAA_BUBBLE = " + json.dumps(bubble, separators=(",", ":")) + ";"
src, n = re.subn(r"const SAA_BUBBLE = \[.*?\];", lambda _m: bub_line, src, count=1, flags=re.S)
assert n == 1, "SAA_BUBBLE line not found in pitchers-embed.js"
embed.write_text(src)
print(f"js/pitchers-embed.js: SAA_DATA -> {len(data)} rows "
      f"({sum(d['hof'] for d in data)} HoF, {sum(d['nel'] for d in data)} NeL, "
      f"{sum(d['role'] == 'RP' for d in data)} relievers), "
      f"SAA_BUBBLE -> {len(bubble)} (#{bubble[0]['rank']}-{bubble[-1]['rank']})")

# ---- SAA_CAREER ----
career = {}
for r in top:
    career[int(r["rank_saa"])] = {
        "role": "Starter" if r["role"] == "SP" else "Reliever",
        "yrs": f"{int(float(r['yr_min']))}–{int(float(r['yr_max']))}",
        "team": r["team"],
        "qip": round(float(r["qualifying_IP"])),
        "w": int(r["W"]), "l": int(r["L"]), "sv": int(r["SV"]), "so": int(r["SO"]),
        "g": int(r["G"]), "gs": int(r["GS"]),
        "ip": round(float(r["IP"])),
        "era": round(float(r["career_ERA"]), 2),
        "whip": round(float(r["career_WHIP"]), 2),
        "eraPlus": None if r["ERA_plus"] in ("", "nan") else round(float(r["ERA_plus"])),
        "war": round(float(r["real_WAR"]), 1),
    }

(HERE / "js/pitchers-career.js").write_text(
    f"// Career lines for the Top {N} SAA pitchers, keyed by SAA rank.\n"
    "// Generated by build_pitchers_js.py from Lahman Pitching + BBRef WAR.\n"
    "const SAA_CAREER = " + json.dumps(career, separators=(",", ":")) + ";\n"
)
print(f"js/pitchers-career.js: SAA_CAREER -> {len(career)} pitchers")

# ---- who just misses (for the "leaves out" writeup) ----
print("\n--- ranks 195-215 ---")
for r in full[194:215]:
    print(f"#{r['rank_saa']:>3} {r['name']:<20} {r['role']}  SAA={float(r['SAA_total']):.2f}  "
          f"{r['W']}-{r['L']}  {float(r['career_ERA']):.2f} ERA  ERA+ {float(r['ERA_plus']):.0f}  "
          f"{float(r['real_WAR']):.0f} bWAR  IP {float(r['IP']):.0f}  {'HOF' if r['hof']=='True' else ''}")
