"""Regenerate the "Your Hall" data module for the hitters side.

Produces js/yourhall-hitters-data.js:
  - YH_CONFIG   category order, the real RHOF default weights, peak/blend/list knobs
  - YH_PLAYERS  every ranked hitter (the full 1,065 pool), each with per-season
                z-scores + PA, so the page can re-score the whole pool under
                user-chosen weights entirely client-side.

Inputs (both from build_saa.py):
  - saa_full.csv             player metadata + the default-weights ranking
  - saa_seasons_hitters.csv  per-season z_AVG/z_ISO/z_BB/z_SB/z_DEF + PA

The default weights / peak window / blend here MUST match build_saa.py
(SAA_WEIGHTS, PEAK_N, and the (total+peak)/2 blend) -- the sanity check at
the bottom re-scores the pool from YH_PLAYERS and asserts it reproduces
saa_full.csv's SAA_final to the digit.
"""
import csv
import json
from collections import defaultdict
from pathlib import Path

from build_cards import hitter_cards

HERE = Path(__file__).resolve().parent

# category order used everywhere on the Your Hall page (matches the table columns
# and build_saa.py's SAA_WEIGHTS): batting avg, isolated power, walk rate,
# stolen-base rate, defense.
CATS = ["avg", "iso", "bb", "sb", "def"]
DEFAULT_WEIGHTS = [0.30, 0.30, 0.10, 0.10, 0.20]
PEAK_N = 7
BLEND = 0.5           # SAA_final = (1-BLEND)*careerTotal + BLEND*peak
LIST_N = 300
BUBBLE_N = 20
PA_NORM = 600.0

hof = set()
for r in csv.DictReader(open(HERE / "HallOfFame.csv")):
    if r["inducted"] == "Y" and r["category"] == "Player":
        hof.add(r["playerID"])

# ---- season matrix, grouped by player ----
seasons_by_pid = defaultdict(list)
for r in csv.DictReader(open(HERE / "saa_seasons_hitters.csv")):
    def z(v):
        # 4 dp reproduces build_saa.py's ranking exactly across the whole pool
        # (3 dp already nails the top 320; 4 dp nails all 1,065) while keeping
        # the file ~625 KB.
        return None if v == "" else round(float(v), 4)
    seasons_by_pid[r["playerID"]].append([
        z(r["z_AVG"]), z(r["z_ISO"]), z(r["z_BB"]), z(r["z_SB"]), z(r["z_DEF"]),
        int(round(float(r["PA"]))),
    ])

# ---- players, in default-ranking order ----
# The five career z's (z2 = PA-weighted average season z, per build_saa.py's
# wavg_skipna) are weight-INDEPENDENT -- they describe the player, not the
# formula -- so they're precomputed here and the table columns never change.
players = []
full = list(csv.DictReader(open(HERE / "saa_full.csv")))
for r in full:
    pid = r["playerID"]
    players.append({
        "id": pid,
        "n": r["name"],
        "hof": pid in hof,
        "nel": r["is_nel_ranked"] == "True",
        "pa": int(round(float(r["career_PA"]))),
        "war": round(float(r["real_WAR"]), 1),
        "z": [round(float(r[k]), 3) for k in
              ("z_AVG_career", "z_ISO_career", "z_BB_career", "z_SB_career", "z_DEF_career")],
        "s": seasons_by_pid[pid],
    })

missing = [p["id"] for p in players if not p["s"]]
assert not missing, f"no season rows for {len(missing)} pool players: {missing[:5]}"

config = {
    "cats": CATS,
    "catLabels": ["AVG", "ISO", "BB", "SB", "DEF"],
    "defaultWeights": DEFAULT_WEIGHTS,
    "defaultPeakN": PEAK_N,
    "defaultBlend": BLEND,
    "listN": LIST_N,
    "bubbleN": BUBBLE_N,
    "paNorm": PA_NORM,
    "pool": len(players),
}

out = (
    "// Per-season z-score matrix for every ranked hitter, so the Your Hall page\n"
    "// can re-score the whole pool under user-chosen weights. Generated by\n"
    "// build_yourhall_js.py from saa_full.csv + saa_seasons_hitters.csv.\n"
    "// season row = [z_AVG, z_ISO, z_BB, z_SB, z_DEF, PA]  (null z = stat absent that year)\n"
    "const YH_CONFIG = " + json.dumps(config, separators=(",", ":")) + ";\n"
    "const YH_PLAYERS = " + json.dumps(players, separators=(",", ":")) + ";\n"
)
(HERE / "js/yourhall-hitters-data.js").write_text(out)
kb = len(out) / 1024
print(f"js/yourhall-hitters-data.js: {len(players)} hitters, "
      f"{sum(len(p['s']) for p in players)} player-seasons, {kb:.0f} KB")

# ---- YH_CARDS: career box-score line per playerID, whole pool ----
# (the Your Hall detail card, same shape as the Top-300 list's SAA_CAREER,
#  but keyed by id since the ranking is recomputed client-side)
war_fallback = {r["playerID"]: float(r["real_WAR"]) for r in full}
cards = hitter_cards({p["id"] for p in players}, war_fallback)
(HERE / "js/yourhall-hitters-cards.js").write_text(
    "// Career box-score lines for every ranked hitter, keyed by playerID.\n"
    "// Generated by build_yourhall_js.py (build_cards.hitter_cards).\n"
    "const YH_CARDS = " + json.dumps(cards, separators=(",", ":")) + ";\n"
)
print(f"js/yourhall-hitters-cards.js: {len(cards)} of {len(players)} hitters have a card")

# ---- sanity check: re-score from YH_PLAYERS, must reproduce saa_full.csv ----
def score(seasons, weights, peak_n, blend):
    saas = []
    for row in seasons:
        num = den = 0.0
        for w, zi in zip(weights, row[:5]):
            if zi is not None:
                num += w * zi
                den += w
        if den > 0:
            saas.append((num / den) * row[5] / PA_NORM)
    total = sum(saas)
    peak = sum(sorted(saas, reverse=True)[:peak_n])
    return (1 - blend) * total + blend * peak

recomputed = sorted(
    ((score(p["s"], DEFAULT_WEIGHTS, PEAK_N, BLEND), p["id"], p["n"]) for p in players),
    reverse=True,
)
worst = 0.0
rank_moves = 0
official = {r["playerID"]: (i + 1, float(r["SAA_final"])) for i, r in enumerate(full)}
for new_rank, (saa, pid, name) in enumerate(recomputed, 1):
    off_rank, off_saa = official[pid]
    worst = max(worst, abs(saa - off_saa))
    if new_rank != off_rank:
        rank_moves += 1
        if rank_moves <= 5:
            print(f"  rank drift: {name} #{off_rank} -> #{new_rank} "
                  f"(saa {off_saa:.4f} vs {saa:.4f})")
print(f"sanity: max |SAA_final - recomputed| = {worst:.2e} over {len(players)} hitters "
      f"(displayed to 2 dp); {rank_moves} rank differences")
assert worst < 1e-3, "client recompute drifts too far from build_saa.py"
assert rank_moves == 0, "recompute reproduces scores but not the ranking order"
print("OK -- client recompute reproduces build_saa.py's ranking exactly")
