"""Build the Stats page data for the pitchers side.

Produces:
  js/stats-pitchers-data.js
    STATS_META      {count, source:"pitchers", qualKey:"ip", qualMin}
    STATS_COLS      [[key, label, type], ...]
    STATS_PITCHERS  [[id, name, yrs, w, l, era, whip, g, gs, cg, sho, sv,
                      ipouts, h, er, hr, bb, so], ...]
                    (career; era/whip pre-formatted strings. The "ip" column
                     holds the raw out count -- the page formats it "X.Y".)
  js/stats-pitchers-seasons.js
    STATS_PITCHERS_SEASONS  {id: [[year, team, w, l, g, gs, cg, sho, sv,
                                   ipouts, h, er, hr, bb, so], ...]}

Reads the Pitching table straight out of lahman_2025.mdb (via access-parser),
majors + Negro Major Leagues, same as build_pitchers_saa.py.
"""
import csv
import json
from collections import defaultdict
from pathlib import Path

from build_bio import player_bio

HERE = Path(__file__).resolve().parent
MDB = HERE / "lahman_2025.mdb"

MAJOR_LGS = {"AL", "NL", "AA", "FL", "PL", "NA", "UA"}
NEGRO_LGS = {"NN1", "NN2", "NNL", "NAL", "ECL", "EWL", "ANL", "NSL"}

# [key, label, sort-type]
COLS = [
    ["name", "Player", "str"], ["yrs", "Yrs", "int"],
    ["w", "W", "num"], ["l", "L", "num"], ["era", "ERA", "rate"], ["whip", "WHIP", "rate"],
    ["g", "G", "num"], ["gs", "GS", "num"], ["cg", "CG", "num"], ["sho", "SHO", "num"],
    ["sv", "SV", "num"], ["ip", "IP", "num"],
    ["h", "H", "num"], ["er", "ER", "num"], ["hr", "HR", "num"], ["bb", "BB", "num"], ["so", "SO", "num"],
]
COUNT = ["W", "L", "G", "GS", "CG", "SHO", "SV", "IPouts", "H", "ER", "HR", "BB", "SO"]


def _int(v):
    try:
        return int(float(v))
    except (TypeError, ValueError):
        return 0


def era(x):
    return "" if x is None else f"{x:.2f}"


def whip_s(x):
    return "" if x is None else f"{x:.3f}"


def main():
    from access_parser import AccessParser
    tbl = AccessParser(str(MDB)).parse_table("Pitching")
    keys = list(tbl.keys())
    rows_raw = list(zip(*(tbl[k] for k in keys)))
    col = {k: i for i, k in enumerate(keys)}

    people = {}
    for r in csv.DictReader(open(HERE / "People.csv")):
        people[r["playerID"]] = f"{r['nameFirst'] or ''} {r['nameLast'] or ''}".strip()

    career = defaultdict(lambda: defaultdict(int))
    yr_min, yr_max = {}, {}
    nel_ids = set()          # pitched >=1 season in a Negro Major League
    season = defaultdict(lambda: defaultdict(lambda: defaultdict(int)))
    season_team = defaultdict(dict)

    for row in rows_raw:
        lg = row[col["lgID"]]
        if lg not in MAJOR_LGS and lg not in NEGRO_LGS:
            continue
        p = row[col["playerID"]]
        if lg in NEGRO_LGS:
            nel_ids.add(p)
        try:
            y = int(row[col["yearID"]])
        except (TypeError, ValueError):
            continue
        for c in COUNT:
            v = _int(row[col[c]])
            career[p][c] += v
            season[p][y][c] += v
        yr_min[p] = min(yr_min.get(p, y), y)
        yr_max[p] = max(yr_max.get(p, y), y)
        season_team[p].setdefault(y, row[col["teamID"]])

    rows = []
    for p, a in career.items():
        outs = a["IPouts"]
        ip = outs / 3.0
        e = a["ER"] * 9 / ip if ip else None
        wh = (a["H"] + a["BB"]) / ip if ip else None
        yrs = f"{yr_min[p]}–{yr_max[p]}" if p in yr_min else ""
        rows.append([
            p, people.get(p, p), yrs,
            a["W"], a["L"], era(e), whip_s(wh),
            a["G"], a["GS"], a["CG"], a["SHO"], a["SV"],
            outs, a["H"], a["ER"], a["HR"], a["BB"], a["SO"],
            1 if p in nel_ids else 0,          # trailing NeL flag
        ])
    rows.sort(key=lambda r: r[12], reverse=True)          # most career outs first

    bio = player_bio({r[0] for r in rows})

    meta = {"count": len(rows), "source": "pitchers", "qualKey": "ip", "qualMin": 9000}
    out = (
        "// One career pitching line per pitcher in the Lahman database.\n"
        "// Generated by build_stats_pitchers_js.py from lahman_2025.mdb + People.csv.\n"
        "// row = [id, name, yrs, W, L, ERA, WHIP, G, GS, CG, SHO, SV, IPouts, H, ER, HR, BB, SO, nel]\n"
        "//   nel = 1 if the pitcher logged a season in a Negro Major League\n"
        "// STATS_BIO[id] = [ht, wt, born, place, bats, throws, debut, final]\n"
        "const STATS_META = " + json.dumps(meta, separators=(",", ":")) + ";\n"
        "const STATS_COLS = " + json.dumps(COLS, separators=(",", ":")) + ";\n"
        "const STATS_BIO = " + json.dumps(bio, separators=(",", ":")) + ";\n"
        "const STATS_PITCHERS = " + json.dumps(rows, separators=(",", ":")) + ";\n"
    )
    (HERE / "js/stats-pitchers-data.js").write_text(out)
    print(f"js/stats-pitchers-data.js: {len(rows)} pitchers ({len(bio)} with bio), "
          f"{len(out) / 1024 / 1024:.2f} MB")

    seasons = {}
    order = ["W", "L", "G", "GS", "CG", "SHO", "SV", "IPouts", "H", "ER", "HR", "BB", "SO"]
    for p, years in season.items():
        seasons[p] = [
            [y, season_team[p][y]] + [years[y][c] for c in order]
            for y in sorted(years)
        ]
    n = sum(len(v) for v in seasons.values())
    sout = (
        "// Season-by-season pitching lines, keyed by playerID -- for the Stats\n"
        "// page's click-to-expand card. Generated by build_stats_pitchers_js.py.\n"
        "// row = [year, team, W, L, G, GS, CG, SHO, SV, IPouts, H, ER, HR, BB, SO]\n"
        "const STATS_PITCHERS_SEASONS = " + json.dumps(seasons, separators=(",", ":")) + ";\n"
    )
    (HERE / "js/stats-pitchers-seasons.js").write_text(sout)
    print(f"js/stats-pitchers-seasons.js: {n} pitcher-seasons, {len(sout) / 1024 / 1024:.2f} MB")


if __name__ == "__main__":
    main()
