"""Build the Stats page data for the batters side.

Produces:
  js/stats-batters-data.js
    STATS_META     {count, ...}
    STATS_COLS     [[key, label], ...]  -- column order for the list table
    STATS_BATTERS  [[id, name, yrs, g, ab, r, h, 2b, 3b, hr, rbi, sb, bb, so,
                     avg, obp, slg, ops], ...]  (career totals; rate stats
                     pre-formatted, "" when undefined)
  js/stats-batters-seasons.js
    STATS_BATTERS_SEASONS  {id: [[year, team, g, ab, r, h, 2b, 3b, hr, rbi,
                                  sb, bb, so, hbp, sf], ...]}  -- one row per
                            season (stints collapsed), chronological, for the
                            click-to-expand card

No RHOF scoring here -- just the raw totals straight from Lahman.
"""
import csv
import json
from collections import defaultdict
from pathlib import Path

from build_bio import player_bio

HERE = Path(__file__).resolve().parent

COUNT_COLS = ["G", "AB", "R", "H", "2B", "3B", "HR", "RBI", "SB", "BB", "SO", "HBP", "SF"]

# [key, label, sort-type]  -- type: str | int | num | rate
COLS = [
    ["name", "Player", "str"], ["yrs", "Yrs", "int"], ["g", "G", "num"],
    ["ab", "AB", "num"], ["r", "R", "num"], ["h", "H", "num"], ["d2", "2B", "num"],
    ["d3", "3B", "num"], ["hr", "HR", "num"], ["rbi", "RBI", "num"], ["sb", "SB", "num"],
    ["bb", "BB", "num"], ["so", "SO", "num"],
    ["avg", "AVG", "rate"], ["obp", "OBP", "rate"], ["slg", "SLG", "rate"], ["ops", "OPS", "rate"],
]


def rate(x):
    """.305  /  1.164  /  "" """
    if x is None:
        return ""
    s = f"{x:.3f}"
    return s[1:] if s.startswith("0.") else s


SEASON_COLS = ["G", "AB", "R", "H", "2B", "3B", "HR", "RBI", "SB", "BB", "SO", "HBP", "SF"]


def _int(v):
    try:
        return int(v or 0)
    except ValueError:
        return 0


def main():
    agg = defaultdict(lambda: defaultdict(int))
    yr_min, yr_max = {}, {}
    # per-player, per-year totals (stints within a year collapsed) + that year's
    # first team, for the click-to-expand season card
    season = defaultdict(lambda: defaultdict(lambda: defaultdict(int)))
    season_team = defaultdict(dict)
    for r in csv.DictReader(open(HERE / "Batting.csv")):
        p = r["playerID"]
        for c in COUNT_COLS:
            agg[p][c] += _int(r[c])
        try:
            y = int(r["yearID"])
        except ValueError:
            continue
        yr_min[p] = min(yr_min.get(p, y), y)
        yr_max[p] = max(yr_max.get(p, y), y)
        for c in SEASON_COLS:
            season[p][y][c] += _int(r[c])
        season_team[p].setdefault(y, r["teamID"])

    people = {}
    for r in csv.DictReader(open(HERE / "People.csv")):
        people[r["playerID"]] = f"{r['nameFirst'] or ''} {r['nameLast'] or ''}".strip()

    rows = []
    for p, a in agg.items():
        ab, h, bb, hbp, sf = a["AB"], a["H"], a["BB"], a["HBP"], a["SF"]
        tb = h + a["2B"] + 2 * a["3B"] + 3 * a["HR"]
        obp_den = ab + bb + hbp + sf
        avg = h / ab if ab else None
        slg = tb / ab if ab else None
        obp = (h + bb + hbp) / obp_den if obp_den else None
        ops = (obp + slg) if (obp is not None and slg is not None) else None
        yrs = f"{yr_min[p]}–{yr_max[p]}" if p in yr_min else ""
        rows.append([
            p, people.get(p, p), yrs,
            a["G"], ab, a["R"], h, a["2B"], a["3B"], a["HR"], a["RBI"],
            a["SB"], bb, a["SO"],
            rate(avg), rate(obp), rate(slg), rate(ops),
        ])

    # default view: most games first (real careers on top, cups of coffee at
    # the bottom), then the search box finds anyone
    rows.sort(key=lambda r: r[3], reverse=True)

    bio = player_bio({r[0] for r in rows})

    meta = {"count": len(rows), "source": "batters", "qualKey": "ab", "qualMin": 1000}
    out = (
        "// One career batting line per player in the Lahman database.\n"
        "// Generated by build_stats_js.py from Batting.csv + People.csv + the .mdb People table.\n"
        "// row = [id, name, yrs, G, AB, R, H, 2B, 3B, HR, RBI, SB, BB, SO, AVG, OBP, SLG, OPS]\n"
        "// STATS_BIO[id] = [ht, wt, born, place, bats, throws, debut, final]\n"
        "const STATS_META = " + json.dumps(meta, separators=(",", ":")) + ";\n"
        "const STATS_COLS = " + json.dumps(COLS, separators=(",", ":")) + ";\n"
        "const STATS_BIO = " + json.dumps(bio, separators=(",", ":")) + ";\n"
        "const STATS_BATTERS = " + json.dumps(rows, separators=(",", ":")) + ";\n"
    )
    (HERE / "js/stats-batters-data.js").write_text(out)
    print(f"js/stats-batters-data.js: {len(rows)} batters ({len(bio)} with bio), "
          f"{len(out) / 1024 / 1024:.1f} MB")

    # ---- per-season lines (for the card) ----
    seasons = {}
    for p, years in season.items():
        seasons[p] = [
            [y, season_team[p][y]] + [years[y][c] for c in
             ("G", "AB", "R", "H", "2B", "3B", "HR", "RBI", "SB", "BB", "SO", "HBP", "SF")]
            for y in sorted(years)
        ]
    n_rows = sum(len(v) for v in seasons.values())
    sout = (
        "// Season-by-season batting lines, keyed by playerID -- for the Stats\n"
        "// page's click-to-expand card. Generated by build_stats_js.py.\n"
        "// row = [year, team, G, AB, R, H, 2B, 3B, HR, RBI, SB, BB, SO, HBP, SF]\n"
        "const STATS_BATTERS_SEASONS = " + json.dumps(seasons, separators=(",", ":")) + ";\n"
    )
    (HERE / "js/stats-batters-seasons.js").write_text(sout)
    print(f"js/stats-batters-seasons.js: {n_rows} player-seasons, {len(sout) / 1024 / 1024:.1f} MB")


if __name__ == "__main__":
    main()
