"""Regenerate the "Your Hall" data modules (hitters and pitchers).

For each side, produces:
  js/yourhall-<side>-data.js
    YH_CONFIG   category order, the real RHOF default weights, list/peak knobs
    YH_PLAYERS  every ranked player (the whole pool), each with:
                  z  = the five weight-INDEPENDENT career z's (table columns)
                  s  = per-season [z0,z1,z2,z3,z4, workload]  (null z = stat
                       absent that year -> renormalise the weights)
  js/yourhall-<side>-cards.js
    YH_CARDS    career box-score line per playerID

The page re-scores the whole pool in the browser under visitor-chosen weights.
The defaults / peak / blend below MUST match build_saa.py / build_pitchers_saa.py
-- the sanity check re-scores the pool from the packed data and asserts it
reproduces the committed ranking to the digit.
"""
import csv
import json
from collections import defaultdict
from pathlib import Path

from build_cards import hitter_cards

HERE = Path(__file__).resolve().parent

HITTERS = dict(
    side="hitters",
    cats=["avg", "iso", "bb", "sb", "def"],
    labels=["AVG", "ISO", "BB", "SB", "DEF"],
    default_weights=[0.30, 0.30, 0.10, 0.10, 0.20],
    peak_n=7,
    blend=0.5,           # score = (1-blend)*careerTotal + blend*best-N peak
    has_peak=True,
    list_n=300,
    workload_norm=600.0,
    z_dp=4,              # per-season z rounding; 4 dp reproduces the ranking
    workload_dp=0,       # PA is integer in the source

    full_csv="saa_full.csv",
    seasons_csv="saa_seasons_hitters.csv",
    season_z_cols=["z_AVG", "z_ISO", "z_BB", "z_SB", "z_DEF"],
    season_workload_col="PA",
    career_z_cols=["z_AVG_career", "z_ISO_career", "z_BB_career", "z_SB_career", "z_DEF_career"],
    workload_col="career_PA",
    nel_col="is_nel_ranked",
)
PITCHERS = dict(
    side="pitchers",
    cats=["era", "whip", "k9", "wpct", "sv"],
    labels=["ERA", "WHIP", "K/9", "WIN%", "SV"],
    default_weights=[0.25, 0.25, 0.20, 0.20, 0.10],
    peak_n=None,
    blend=None,
    has_peak=False,      # pitcher SAA is the career total only -- no peak/blend
    list_n=150,
    workload_norm=200.0,
    z_dp=5,              # IP is fractional, so both z and IP need more places
    workload_dp=3,       # than the hitters side to reproduce the ranking exactly

    full_csv="saa_pitchers_full.csv",
    seasons_csv="saa_seasons_pitchers.csv",
    season_z_cols=["z_era", "z_whip", "z_k9", "z_wpct", "z_sv"],
    season_workload_col="IP",
    career_z_cols=["z_era", "z_whip", "z_k9", "z_wpct", "z_sv"],
    workload_col="IP",
    nel_col="is_nel_ranked",
)
BUBBLE_N = 20

hof = set()
for r in csv.DictReader(open(HERE / "HallOfFame.csv")):
    if r["inducted"] == "Y" and r["category"] == "Player":
        hof.add(r["playerID"])


def build(cfg):
    full = list(csv.DictReader(open(HERE / cfg["full_csv"])))
    zdp, wdp = cfg["z_dp"], cfg["workload_dp"]

    def zval(v):
        return None if v in ("", "nan") else round(float(v), zdp)

    seasons_by_pid = defaultdict(list)
    for r in csv.DictReader(open(HERE / cfg["seasons_csv"])):
        row = [zval(r[c]) for c in cfg["season_z_cols"]]
        wl = float(r[cfg["season_workload_col"]])
        row.append(int(round(wl)) if wdp == 0 else round(wl, wdp))
        seasons_by_pid[r["playerID"]].append(row)

    players = []
    for r in full:
        pid = r["playerID"]
        players.append({
            "id": pid,
            "n": r["name"],
            "hof": pid in hof,
            "nel": r[cfg["nel_col"]] == "True",
            "wl": int(round(float(r[cfg["workload_col"]]))),
            "z": [round(float(r[c]), 3) for c in cfg["career_z_cols"]],
            "s": seasons_by_pid[pid],
        })
    missing = [p["id"] for p in players if not p["s"]]
    assert not missing, f"{cfg['side']}: no season rows for {len(missing)}: {missing[:5]}"

    config = {
        "mode": cfg["side"],
        "cats": cfg["cats"],
        "catLabels": cfg["labels"],
        "defaultWeights": cfg["default_weights"],
        "hasPeak": cfg["has_peak"],
        "defaultPeakN": cfg["peak_n"],
        "defaultBlend": cfg["blend"],
        "listN": cfg["list_n"],
        "bubbleN": BUBBLE_N,
        "workloadNorm": cfg["workload_norm"],
        "pool": len(players),
    }
    wl_label = cfg["season_workload_col"]
    out = (
        f"// Per-season z-score matrix for every ranked {cfg['side'][:-1]}, so the Your Hall\n"
        f"// page can re-score the whole pool under user-chosen weights. Generated by\n"
        f"// build_yourhall_js.py.  season row = [z, z, z, z, z, {wl_label}]  "
        f"({'/'.join(cfg['labels'])}; null z = stat absent that year)\n"
        "const YH_CONFIG = " + json.dumps(config, separators=(",", ":")) + ";\n"
        "const YH_PLAYERS = " + json.dumps(players, separators=(",", ":")) + ";\n"
    )
    (HERE / f"js/yourhall-{cfg['side']}-data.js").write_text(out)
    print(f"js/yourhall-{cfg['side']}-data.js: {len(players)} {cfg['side']}, "
          f"{sum(len(p['s']) for p in players)} player-seasons, {len(out) / 1024:.0f} KB")

    _sanity(cfg, players, full)
    _cards(cfg, players, full)


def _score(seasons, weights, peak_n, blend, norm, has_peak):
    saas = []
    total = 0.0
    for row in seasons:
        num = den = 0.0
        for w, zi in zip(weights, row[:5]):
            if zi is not None:
                num += w * zi
                den += w
        if den > 0:
            v = (num / den) * row[5] / norm
            saas.append(v)
            total += v
    if not has_peak:
        return total
    peak = sum(sorted(saas, reverse=True)[:peak_n])
    return (1 - blend) * total + blend * peak


def _sanity(cfg, players, full):
    official_key = "SAA_final" if cfg["has_peak"] else "SAA_total"
    official = {r["playerID"]: (i + 1, float(r[official_key])) for i, r in enumerate(full)}
    rec = sorted(
        ((_score(p["s"], cfg["default_weights"], cfg["peak_n"], cfg["blend"],
                 cfg["workload_norm"], cfg["has_peak"]), p["id"], p["n"]) for p in players),
        reverse=True,
    )
    worst = 0.0
    moves = 0
    for new_rank, (saa, pid, name) in enumerate(rec, 1):
        off_rank, off_saa = official[pid]
        worst = max(worst, abs(saa - off_saa))
        if new_rank != off_rank:
            moves += 1
            if moves <= 4:
                print(f"  {cfg['side']} rank drift: {name} #{off_rank} -> #{new_rank}")
    print(f"  sanity: max |score - recomputed| = {worst:.2e}; {moves} rank differences")
    assert worst < 1e-3, f"{cfg['side']}: client recompute drifts too far"
    assert moves == 0, f"{cfg['side']}: recompute does not reproduce the ranking order"


def _cards(cfg, players, full):
    ids = {p["id"] for p in players}
    if cfg["side"] == "hitters":
        war_fallback = {r["playerID"]: float(r["real_WAR"]) for r in full}
        cards = hitter_cards(ids, war_fallback)
    else:
        cards = {}
        for r in full:
            eplus = r["ERA_plus"]
            cards[r["playerID"]] = {
                "role": "Starter" if r["role"] == "SP" else "Reliever",
                "yrs": f"{int(float(r['yr_min']))}–{int(float(r['yr_max']))}",
                "team": r["team"],
                "qip": round(float(r["qualifying_IP"])),
                "w": int(r["W"]), "l": int(r["L"]), "sv": int(r["SV"]), "so": int(r["SO"]),
                "g": int(r["G"]), "gs": int(r["GS"]),
                "ip": round(float(r["IP"])),
                "era": round(float(r["career_ERA"]), 2),
                "whip": round(float(r["career_WHIP"]), 2),
                "eraPlus": None if eplus in ("", "nan") else round(float(eplus)),
                "war": round(float(r["real_WAR"]), 1),
            }
    (HERE / f"js/yourhall-{cfg['side']}-cards.js").write_text(
        f"// Career box-score lines for every ranked {cfg['side'][:-1]}, keyed by playerID.\n"
        "// Generated by build_yourhall_js.py.\n"
        "const YH_CARDS = " + json.dumps(cards, separators=(",", ":")) + ";\n"
    )
    print(f"js/yourhall-{cfg['side']}-cards.js: {len(cards)} of {len(players)} have a card")


if __name__ == "__main__":
    build(HITTERS)
    build(PITCHERS)
    print("OK -- both Your Hall sides reproduce the committed ranking exactly")
