"""Build the Stats page data: one career batting line for every player in the
Lahman database (everyone who appears in Batting.csv).

Produces js/stats-batters-data.js:
  STATS_META     {count, ...}
  STATS_COLS     [[key, label], ...]  -- column order, matches the row arrays
  STATS_BATTERS  [[id, name, yrs, g, ab, r, h, 2b, 3b, hr, rbi, sb, bb, so,
                   avg, obp, slg, ops], ...]  (rate stats are pre-formatted
                   strings, "" when undefined)

No RHOF scoring here -- just the raw career totals straight from Lahman.
"""
import csv
import json
from collections import defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent

COUNT_COLS = ["G", "AB", "R", "H", "2B", "3B", "HR", "RBI", "SB", "BB", "SO", "HBP", "SF"]

COLS = [
    ["name", "Player"], ["yrs", "Yrs"], ["g", "G"], ["ab", "AB"], ["r", "R"],
    ["h", "H"], ["d2", "2B"], ["d3", "3B"], ["hr", "HR"], ["rbi", "RBI"],
    ["sb", "SB"], ["bb", "BB"], ["so", "SO"],
    ["avg", "AVG"], ["obp", "OBP"], ["slg", "SLG"], ["ops", "OPS"],
]


def rate(x):
    """.305  /  1.164  /  "" """
    if x is None:
        return ""
    s = f"{x:.3f}"
    return s[1:] if s.startswith("0.") else s


def main():
    agg = defaultdict(lambda: defaultdict(int))
    yr_min, yr_max = {}, {}
    for r in csv.DictReader(open(HERE / "Batting.csv")):
        p = r["playerID"]
        for c in COUNT_COLS:
            try:
                agg[p][c] += int(r[c] or 0)
            except ValueError:
                pass
        try:
            y = int(r["yearID"])
            yr_min[p] = min(yr_min.get(p, y), y)
            yr_max[p] = max(yr_max.get(p, y), y)
        except ValueError:
            pass

    people = {}
    for r in csv.DictReader(open(HERE / "People.csv")):
        people[r["playerID"]] = f"{r['nameFirst'] or ''} {r['nameLast'] or ''}".strip()

    rows = []
    for p, a in agg.items():
        ab, h, bb, hbp, sf = a["AB"], a["H"], a["BB"], a["HBP"], a["SF"]
        tb = h + a["2B"] + 2 * a["3B"] + 3 * a["HR"]
        obp_den = ab + bb + hbp + sf
        avg = h / ab if ab else None
        slg = tb / ab if ab else None
        obp = (h + bb + hbp) / obp_den if obp_den else None
        ops = (obp + slg) if (obp is not None and slg is not None) else None
        yrs = f"{yr_min[p]}–{yr_max[p]}" if p in yr_min else ""
        rows.append([
            p, people.get(p, p), yrs,
            a["G"], ab, a["R"], h, a["2B"], a["3B"], a["HR"], a["RBI"],
            a["SB"], bb, a["SO"],
            rate(avg), rate(obp), rate(slg), rate(ops),
        ])

    # default view: most games first (real careers on top, cups of coffee at
    # the bottom), then the search box finds anyone
    rows.sort(key=lambda r: r[3], reverse=True)

    meta = {"count": len(rows), "source": "batters"}
    out = (
        "// One career batting line per player in the Lahman database.\n"
        "// Generated by build_stats_js.py from Batting.csv + People.csv.\n"
        "// row = [id, name, yrs, G, AB, R, H, 2B, 3B, HR, RBI, SB, BB, SO, AVG, OBP, SLG, OPS]\n"
        "const STATS_META = " + json.dumps(meta, separators=(",", ":")) + ";\n"
        "const STATS_COLS = " + json.dumps(COLS, separators=(",", ":")) + ";\n"
        "const STATS_BATTERS = " + json.dumps(rows, separators=(",", ":")) + ";\n"
    )
    (HERE / "js/stats-batters-data.js").write_text(out)
    print(f"js/stats-batters-data.js: {len(rows)} batters, {len(out) / 1024 / 1024:.1f} MB")


if __name__ == "__main__":
    main()
