"""
SAA validation, pitcher side: the same Hall-of-Fame hit-rate test
build_validation.py runs for hitters, run against the pitcher pool.

For every pitcher in the SAA qualifying pool this joins:
  - SAA_total            (this site's pitcher metric -- no peak/blend, unlike hitters)
  - bWAR / bWAA / JAWS    Baseball-Reference, pitching side only

war_daily_pitch.txt keys on the BBRef id, which differs from the Lahman
playerID for a handful of pitchers -- bridged via People.csv's bbrefID,
same approach build_pitchers_saa.py uses for career bWAR.

Output: js/validation-pitchers-data.js -- the numbers the Validation page's
second ("Picking the Hall" / pitchers) table renders from.
"""

import json
import pandas as pd
from pathlib import Path
from scipy.stats import spearmanr

HERE = Path(__file__).parent
WAR7_N = 7


def pitcher_season_metrics():
    war = pd.read_csv(HERE / "war_daily_pitch.txt", usecols=["player_ID", "year_ID", "WAR", "WAA"])
    war["WAR"] = pd.to_numeric(war["WAR"], errors="coerce").fillna(0.0)
    war["WAA"] = pd.to_numeric(war["WAA"], errors="coerce").fillna(0.0)
    ps = war.groupby(["player_ID", "year_ID"], as_index=False)[["WAR", "WAA"]].sum()

    def per_player(d):
        war7 = d["WAR"].sort_values(ascending=False).head(WAR7_N).sum()
        total = d["WAR"].sum()
        return pd.Series({"bWAR": total, "bWAA": d["WAA"].sum(),
                          "JAWS": (total + war7) / 2.0})
    return ps.groupby("player_ID").apply(per_player).reset_index()


def rank_desc(s):
    return s.rank(ascending=False, method="min")


def main():
    saa = pd.read_csv(HERE / "saa_pitchers_full.csv")
    people = pd.read_csv(HERE / "People.csv")[["playerID", "bbrefID"]]
    saa = saa.merge(people, on="playerID", how="left")

    cm = pitcher_season_metrics()
    df = saa.merge(cm, left_on="bbrefID", right_on="player_ID", how="left")

    # hof / is_nel_ranked are written as Python bools by build_pitchers_saa.py,
    # which pandas round-trips through CSV as the strings "True"/"False"
    df["hof"] = df["hof"].astype(str) == "True"
    df["is_nel_ranked"] = df["is_nel_ranked"].astype(str) == "True"

    for col, r in [("SAA_total", "saa_rank"), ("bWAR", "bwar_rank"),
                   ("bWAA", "bwaa_rank"), ("JAWS", "jaws_rank")]:
        df[r] = rank_desc(df[col])

    # Negro Leagues pitchers held out, same reasoning as the hitter build:
    # their bWAR is built on a far shorter official league schedule, so a
    # rank against it isn't comparable to SAA's normalized carve-out.
    c = df.dropna(subset=["bWAR", "bWAA", "JAWS"])
    c = c[~c["is_nel_ranked"]].copy()

    print(f"{len(c)} pitchers in the SAA pool with a Baseball-Reference pitching-WAR record")

    print("\n--- Spearman rank correlation (whole pool) ---")
    corr = {"n": int(len(c))}
    for lab, col, key in [("bWAR", "bWAR", "war"), ("bWAA", "bWAA", "waa"), ("JAWS", "JAWS", "jaws")]:
        val = spearmanr(c["SAA_total"], c[col]).correlation
        corr[key] = round(val, 2)
        print(f"  SAA_total vs {lab:5s} : {val:.3f}")

    n_hof = int(c["hof"].sum())
    print(f"\n--- Hall-of-Fame hit rate: how many of the top-N are BBWAA/Vet inductees ---")
    print(f"  (pool contains {n_hof} inducted pitchers out of {len(c)})")
    hof_rows = []
    for n in (50, 100, 150):
        row = {"n": n}
        for key, col in [("saa", "SAA_total"), ("war", "bWAR"), ("waa", "bWAA"), ("jaws", "JAWS")]:
            row[key] = int(c.nlargest(n, col)["hof"].sum())
        hof_rows.append(row)
        print(f"  top {n:>3} | SAA {row['saa']:>3}/{n} | bWAR {row['war']:>3}/{n} "
              f"| bWAA {row['waa']:>3}/{n} | JAWS {row['jaws']:>3}/{n}")

    payload = {
        "pool_n": int(len(c)),
        "hof_n": n_hof,
        "corr": corr,
        "hof": hof_rows,
    }
    js = ("// SAA vs Baseball-Reference WAR / WAA / JAWS -- pitcher side.\n"
          "// Generated by build_validation_pitchers.py from saa_pitchers_full.csv "
          "+ war_daily_pitch.txt + People.csv.\n"
          "const VALIDATION_PITCHERS = " + json.dumps(payload, separators=(",", ":")) + ";\n")
    (HERE / "js" / "validation-pitchers-data.js").write_text(js)
    print(f"\nWrote js/validation-pitchers-data.js ({len(js):,} bytes)")


if __name__ == "__main__":
    main()
